---
- name: Enable rclone-sync service
  ansible.builtin.service:
    name: rclone-sync.timer
    state: restarted
    enabled: yes
  when: "(rclone_sync_systemd | default({'changed': true})) is changed"
