### Setup UI Language
setupuilanguage=en

### Language Packs Selected to Install
selectedlanguagepacks=en

### Required parameter to accept the SAP license agreement for upgrades
AGREE_TO_SAP_LICENSE=true
