---
- name: Debug resolved AWS environment for ARNS secret lookup
  ansible.builtin.debug:
    msg: "onr_arns_environment_suffix={{ onr_arns_environment_suffix }}"

- name: Retrieve ARNS RDS details from AWS Secrets Manager
  shell: |
    export PATH=$PATH:/usr/local/bin
    aws secretsmanager get-secret-value --secret-id {{ onr_arns_secret_id }} --region {{ onr_arns_aws_region }} --query SecretString --output text
  changed_when: false
  register: onr_arns_secret_result
#  no_log: true

- name: Parse ARNS Secrets Manager secret
  ansible.builtin.set_fact:
    onr_arns_secret: "{{ onr_arns_secret_result.stdout | from_json }}"
  no_log: true

- name: Set ARNS connection values
  ansible.builtin.set_fact:
    onr_arns_db_username: >-
      {{ onr_arns_secret[onr_arns_secret_username_key] }}
    onr_arns_db_password: >-
      {{ onr_arns_secret[onr_arns_secret_password_key] }}
    onr_arns_db_host: >-
      {{ onr_arns_secret[onr_arns_secret_host_key] }}
    onr_arns_db_port: >-
      {{ onr_arns_secret[onr_arns_secret_port_key] | default(5432) }}
    onr_arns_db_name: >-
      {{ onr_arns_secret[onr_arns_secret_database_key] }}
  no_log: true