---
- name: Download ARNS PostgreSQL CA certificate from S3
  amazon.aws.s3_object:
    bucket: "{{ s3_bucket }}"
    object: >-
      {{ onr_arns_certificate_s3_prefix }}/{{ onr_arns_certificate_filename }}
    dest: "{{ onr_arns_certificate_path }}"
    mode: get

- name: Set permissions on ARNS PostgreSQL CA certificate
  ansible.builtin.file:
    path: "{{ onr_arns_certificate_path }}"
    owner: root
    group: root
    mode: "0644"

- name: Update operating system CA trust
  ansible.builtin.command:
    cmd: update-ca-trust extract
  changed_when: true