plugin: amazon.aws.aws_ec2
regions:
  - eu-west-2
include_filters:
  - tag:aws:autoscaling:groupName:
      - "*"
exclude_filters:
  - instance-state-name:
      - pending
      - shutting-down
      - terminated
      - stopping
      - stopped
  - tag:os-type:
      - Windows
hostnames:
  - "instance-id"

compose:
  application: tags['application']
  aws_environment: tags['environment-name'].split('-')|last
  ec2_name: tags['Name']
  ec2_connection_type: >
    'ssh' if tags['server-type'] in ['nomis-web'] else 'ssm'

keyed_groups:
  - key: tags['environment-name']
    prefix: environment-name
  - key: tags['environment-name'] + '-' + tags[application + '-environment']
    prefix: environment-name
  - key: tags['ami']
    prefix: ami
  - key: tags['server-type']
    prefix: server-type
  - key: tags['server-type'] + '-' + tags[application + '-environment']
    prefix: server-type
  - key: tags['os-type'] | lower
    prefix: os-type

strict: no
