plugin: amazon.aws.aws_ec2
regions:
  - eu-west-2
include_filters:
  - tag:aws:autoscaling:groupName:
      - "*"
exclude_filters:
  - instance-state-name:
      - pending
      - shutting-down
      - terminated
      - stopping
      - stopped
  - tag:os-type:
      - Windows
hostnames:
  - "instance-id"

compose:
  application: tags['application']
  aws_environment: tags['environment-name'].split('-')|last
  ec2_name: tags['Name']
  ansible_host: >-
    private_ip_address
    if (tags.get('connection-type') == 'ssh' or ('connection-type' not in tags and tags.get('server-type') in ['nomis-web']))
    else instance_id

keyed_groups:
  - key: >-
      tags.get('connection-type')
      if tags.get('connection-type')
      else ('ssh' if tags.get('server-type') in ['nomis-web'] else 'ssm')
    prefix: connection_type
  - key: tags['environment-name']
    prefix: environment-name
  - key: tags['environment-name'] + '-' + tags[application + '-environment']
    prefix: environment-name
  - key: tags['ami']
    prefix: ami
  - key: tags['server-type']
    prefix: server-type
  - key: tags['server-type'] + '-' + tags[application + '-environment']
    prefix: server-type
  - key: tags['os-type'] | lower
    prefix: os-type

strict: no
