---

# grant db trigger

- name: Define Backup Directory for expire password script
  set_fact:
     backup_dir: /u02/stage/{{ db_name }}/
  tags: 
  - preactions
  - 10gpwd

- name: Create Backup Directory
  file:
     path: "{{ backup_dir }}"
     state: directory
  tags: 
  - preactions
  - d10gpwd

- name: Run expire accounts with 10G format passwords
  environment: "{{ oracle11g_env }}"
  script: run_expire10gformat_accounts.sh
  tags: 
  - preactions
  - 10gpwd

