---

- name: Re-set 10g passwords
  become: true
  become_user: oracle
  environment: "{{ oracle19c_env }}"
  script: "run_{{ db_name }}_postupgrade.sh"
  register:  postupgrade_run
  tags:
      - postupgrade
      - instancespecific
  when: database_role == "PRIMARY"

   #- name: Set Default RMAN Tape Channel
     #script: set_default_rman_channel.sh


- name: Install 19c Apex
  become: true
  become_user: oracle
  environment: "{{ oracle19c_env }}"
  script: run_Install19cApex.sh
  tags:
      - postupgrade
      - instancespecific
  when: database_role == "PRIMARY"

- name: Run Recompile INDIVIDUAL OBJECTS
  become: true
  become_user: oracle
  environment: "{{ oracle19c_env }}"
  script: run_recompile_triggers.sh
  register: run_recompile
  tags:
  - postupgrade
  - recompile
- name: Show Recompilation Results
  debug: var=run_recompile.stdout_lines
  tags:
      - postupgrade
      - recompile
      - debug

- name: Install JSON for Nomis API
  become: true
  become_user: oracle
  environment: "{{ oracle19c_env }}"
  script: run_InstallJSonNomisAPI.sh
  tags:
      - postupgrade
      - instancespecific      
  when: database_role == "PRIMARY"

- name: Run Recompiliation
  become: true
  become_user: oracle
  environment: "{{ oracle19c_env }}"
  script: run_recompile.sh
  register: run_recompile
  tags:
  - postupgrade
  - recompile
- name: Show Recompilation Results
  debug: var=run_recompile.stdout_lines
  tags:
      - postupgrade
      - recompile
      - debug

