---

- name: Get Database Status
  shell: |
         . ~/.bash_profile
         srvctl status database -d {{ database_primary_sid | default(database_standby_sid) }}
  register: database_status
  changed_when: false

- name: Startup Database
  shell: |
         . ~/.bash_profile
         srvctl start database -d {{ database_primary_sid | default(database_standby_sid) }}
  when: database_status.stdout is search("Database is not running.")
