---
# See README.md for examples
# Note: --ignore-size and --ignore-checksum is required for some file types, e.g. xlsx

rclone_sync_config:
  # shared_lock: "" # optionally set to file share directory for locking
  rclone_args: {}
  #   - "--stats=0"
  #   - "--fast-list"
  dirs: {}
  #  example:
  #    rclone_cmd:
  #      - "copy"
  #      - "/my/sourcedir"
  #      - "rclongconfig:sharepoint/path"
  #    rclone_args:
  #      - "--min-age=2m"
  #      - "--include=*.xlsx"
  #      - "--ignore-size"  # because MS365 immediately updates xlsx files
  #      - "--ignore-checksum"  # ditto
  #      - "--max-depth=1"

rclone_sync_description: "Script for running rclone against multiple local directories on a timer"
rclone_sync_timer_frequency_minutes: 5
rclone_sync_timer_start_minute: "{{ (ec2_name.split('-')[-1] | int) % rclone_sync_timer_frequency_minutes }}"
rclone_sync_timer_schedule: "*:{{ rclone_sync_timer_start_minute }}/{{ rclone_sync_timer_frequency_minutes }}"
