database_standby_unique: PRDMISS1
database_standby_sid: PRDMISS1
database_parameters:
  control_management_pack_access: DIAGNOSTIC+TUNING
  sga_max_size: 175G
  sga_target: 175G
  pga_aggregate_target: 35G
  pga_aggregate_limit: 70G
data_guard_parameters:
  ApplyLagThreshold: 1000
db_backup_s3_bucket_name: "{{ environment_name }}-oracle-mis-db-backups"
required_patches:
   p35413661:
      patch_files:
        - target_version: "19.28"
          filename: p35413661_1928000DBRU_Linux-x86-64.zip
      description: "ORA-600 [OPTDESC] ASSERT NEED TO BE INTRODUCED EARLIER IN QKNA INSTEAD OF QERIX"
      grid_patch: false
      database_patch: true