---
ansible_aws_ssm_bucket_name: s3-bucket20240321144737986100000001
dns_zone_internal: oasys-national-reporting.hmpps-production.modernisation-platform.internal
onr_environment: "{{ ec2.tags['oasys-national-reporting-environment'] }}"

filesystems_domain_name_fqdn: azure.hmpp.root
filesystems_domains:
  azure.hmpp.root:
    secret_name: /sap/bip/pd/passwords
    mount_fs_username: svc_fsx_nart

bip_filesystems_mount:
  - dir: /opt/data/BusinessObjects
    fstype: nfs
    uid: bobj
    gid: binstall
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,nofail
    src: "fs-082eb379ce8caf385.efs.eu-west-2.amazonaws.com:/"
    metric_dimension: pd_onr_sap_share
    maintenance_window:
  - dir: /NART
    uid: bobj
    gid: binstall
    fstype: cifs
    opts: vers=3.0,_netdev,nofail,uid=1201,gid=1201,dir_mode=0755,file_mode=0755,credentials=/root/.filesystems/azure.hmpp.root.creds
    src: //fslinux.azure.hmpp.root/NART$
    # metric_dimension: NART
    maintenance_window: "4.0400-4.0430" # Thu 4am UTC
    state: absent
    autofs_mount: true

sap_web_filesystems_mount:
  - dir: /NART
    uid: bobj
    gid: binstall
    fstype: cifs
    opts: vers=3.0,_netdev,nofail,uid=1201,gid=1201,dir_mode=0755,file_mode=0755,credentials=/root/.filesystems/azure.hmpp.root.creds
    src: //fslinux.azure.hmpp.root/NART$
    # metric_dimension: NART
    maintenance_window: "4.0400-4.0430" # Thu 4am UTC
    state: absent
    autofs_mount: true

# For some reason pd-onr-db-1-a was added to the oasys-production environment instead of this environment.
# See environment_name_oasys_production.yml for the db_config for the databases.

oracle_client_tnsnames_ora_source_filename: "tnsnames.ora.onr-bip.{{ onr_environment }}"
oracle_client_sqlnet_ora_source_filename: sqlnet.ora

sap_bip_confs:
  pd:
    sap_web_java_mem: "4096"
    sap_bip_rar_base: "BIPLATS4304P_500-70002683"
    sap_bip_rws_url: "https://reporting.oasys.service.justice.gov.uk/biprws"
    sap_bip_auditing_db_server: PDBOAUD
    sap_bip_auditing_db_user: bip_audit_owner
    sap_bip_cms_db_server: PDBOSYS
    sap_bip_cms_db_user: bip_system_owner
    sap_bip_control_app_servers:
    sap_bip_control_cms_servers: |
      AdaptiveJobServer,Running,Enabled
      AdaptiveProcessingServer,Running,Enabled
      APS.Auditing,Running,Enabled
      APS.Connectivity,Running,Enabled
      APS.PromotionManagement,Running,Enabled
      CentralManagementServer,Running,Enabled
      ConnectionServer,Running,Enabled
      EventServer,Running,Enabled
      InputFileRepository,Running,Enabled
      OutputFileRepository,Running,Enabled
      WebApplicationContainerServer,Running,Enabled
      WebIntelligenceProcessingServer,Running,Enabled
      WebiDSLBridge,Stopped,Disabled
    sap_bip_control_cms_server_1: |
      APS.Search,Running,Enabled
    sap_bip_control_cms_server_2: |
      APS.Search,Running,Enabled

sap_environment: "{{ onr_environment }}"
sap_bip_conf: "{{ sap_bip_confs[sap_environment] }}"
sap_bip_control_public_lb_name: public-lb
sap_bip_control_app_servers: "{{ sap_bip_conf.sap_bip_control_app_servers }}"
sap_bip_control_cms_servers: "{{ sap_bip_conf.sap_bip_control_cms_servers }}"
sap_bip_control_cms_server_1: "{{ sap_bip_conf.sap_bip_control_cms_server_1 }}"
sap_bip_control_cms_server_2: "{{ sap_bip_conf.sap_bip_control_cms_server_2 }}"
sap_bip_rar_base: "{{ sap_bip_conf.sap_bip_rar_base }}"
sap_bip_rws_url: "{{ sap_bip_conf.sap_bip_rws_url }}"
sap_bip_auditing_db_server: "{{ sap_bip_conf.sap_bip_auditing_db_server }}"
sap_bip_auditing_db_user: "{{ sap_bip_conf.sap_bip_auditing_db_user }}"
sap_bip_cms_db_server: "{{ sap_bip_conf.sap_bip_cms_db_server }}"
sap_bip_cms_db_user: "{{ sap_bip_conf.sap_bip_cms_db_user }}"
