#!/bin/bash
#
# check's overall health of weblogic server
#
#

case "$1" in
start)
    nohup /etc/healthcheck/healthcheck.sh > /var/log/healthcheck.log 2>&1 &
    echo $! > /var/run/healthcheck.pid
    ;;
stop)
    kill "$(cat /var/run/healthcheck.pid)"
    rm -f /var/run/healthcheck.pid
    ;;
restart)
    $0 stop
    $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;  
esac

exit 0