#!/bin/bash
#
# {{ weblogic_managed_server_name }}        Startup script for managed server.
#
# chkconfig: - 76 14
# description: weblogic managed server {{ weblogic_managed_server_name }}

# Source function library.
. /etc/init.d/functions

prog="{{ weblogic_managed_server_name }}"

start_process() {
  if [[ $(whoami) == "root" ]]; then
    nohup su - oracle -c ". /u01/app/oracle/Middleware/wlserver_10.3/server/bin/setWLSEnv.sh && . /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/bin/setDomainEnv.sh && /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/bin/startManagedWebLogic.sh {{ weblogic_managed_server_name }}" 2>&1 | logger -p local3.info -t "$prog" &
  else
    echo -n "must be run as root"
    return 1
  fi
}

wait_process() {
  timeout 290 /home/oracle/admin/scripts/wait_for_entry_in_log.sh /var/log/messages "Server started in RUNNING mode" "$prog:"
}

stop_process() {
  if [[ $(whoami) == "root" ]]; then
    nohup su - oracle -c ". /u01/app/oracle/Middleware/wlserver_10.3/server/bin/setWLSEnv.sh && . /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/bin/setDomainEnv.sh && /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/bin/stopManagedWebLogic.sh {{ weblogic_managed_server_name }}" 2>&1 | logger -p local3.info -t "$prog" &
  else
    echo -n "must be run as root"
    return 1
  fi
}

get_process_pids() {
  process_pids1=$(pgrep -u oracle -f "startManagedWebLogic.sh {{ weblogic_managed_server_name }}$" 2> /dev/null)
  process_pids2=$(pgrep -u oracle -f "weblogic.Name={{ weblogic_managed_server_name }} " 2> /dev/null)
  [[ -z $process_pids1 && -z $process_pids2 ]] && return 1
  (
    for process_pid in $process_pids1 $process_pids2; do
      pstree -ap "$process_pid" | grep -v '{' | cut -d, -f2 | cut -d\  -f1
    done
  ) | sort -u | tr '\n' ' '
}

start() {
  echo -n $"Starting $prog: "
  if PIDS=$(get_process_pids); then
    echo -n "Already running"
    echo_success
    echo
    return 0
  fi
  echo "init.d starting $prog" | logger -p local3.info -t "$prog"
  if ! start_process; then
    echo "init.d failed starting $prog" | logger -p local3.info -t "$prog"
    echo_failure
    echo
    return 1
  fi
  if ! wait_process; then
    echo "init.d failed waiting for $prog" | logger -p local3.info -t "$prog"
  fi
  if ! get_process_pids > /dev/null; then
    echo "init.d failed getting process pids for $prog" | logger -p local3.info -t "$prog"
    echo_failure
    echo
    return 1
  fi
  echo "init.d started $prog" | logger -p local3.info -t "$prog"
  echo_success
  echo
}

stop() {
  echo -n $"Shutting down $prog: "
  if ! PIDS=$(get_process_pids); then
    echo -n "Already stopped"
    echo_success
    echo
    return 0
  fi
  echo "init.d stopping $prog" | logger -p local3.info -t "$prog"
  stop_process
  sleep 2
  if ! PIDS=$(get_process_pids); then
    echo_success
    echo
    return 0
  fi
  echo "init.d killing $prog $PIDS" | logger -p local3.info -t "$prog"
  kill $PIDS
  sleep 2
  if ! get_process_pids > /dev/null; then
    echo_success
    echo
    return 0
  fi
  sleep 5
  if ! PIDS=$(get_process_pids); then
    echo_success
    echo
    return 0
  fi
  echo "init.d killing with -9 $prog $PIDS" | logger -p local3.info -t "$prog"
  kill -9 $PIDS
  sleep 2
  if ! get_process_pids > /dev/null; then
    echo_success
    echo
    return 0
  fi
  echo_failure
  echo
  return 1
}

status() {
  echo -n $"Status of $prog: "
  if ! PIDS=$(get_process_pids); then
    echo -n "process not found"
    echo_failure
    echo
    return 1
  fi
  echo -n "$PIDS"
  echo_success
  echo
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 3
esac

exit $?
