- name: Set Secret Name for the RAT Users
  set_fact:
    secret_name: "{{ environment_name }}-oracle{% if 'delius-mis' in environment_name %}-{{ database_primary_sid[-3:] | lower }}{% endif %}-db-dba-passwords"
    users: [rat_capture, rat_replay]

- name: Setup Temporary Secrets Dictionary
  set_fact:
    secret_password_dict:
      account:
        secret: "{{ secret_name }}"

- name: Check User Exists In Secret
  shell: aws secretsmanager get-secret-value --secret-id {{ secret_name }} --region {{ region }} --query SecretString --output text| jq -r .{{ item }}
  loop: "{{ users }}"
  register: secret_users
  no_log: true

- name: Add User Passwords Which Do Not Exist
  set_fact:
    add_users: |
      {{ add_users | default([]) + [{item.item: 'auto'} ] }}
  loop: "{{ secret_users.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.stdout == 'null'

- name: Add User Passwords Which Do Exist
  set_fact:
    add_users: |
      {{ add_users | default([]) + [{item.item: None} ] }}
  loop: "{{ secret_users.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.stdout != 'null'

- name: Add Users To Secret Dictionary
  set_fact:
    secret_password_dict: "{{ secret_password_dict | combine({ 'account': { 'users': add_users }}, recursive=true) }}"

- name: Get Secret Passwords
  import_role:
    name: secretsmanager-passwords
  vars:
    secretsmanager_passwords: "{{ secret_password_dict }}"
  when: is_aws_environment | default(true)
  no_log: true

- name: Set Secret Passwords
  set_fact:
    rat_capture_password: "{{ secretsmanager_passwords_dict['account'].passwords['rat_capture'] }}"
    rat_replay_password: "{{ secretsmanager_passwords_dict['account'].passwords['rat_replay'] }}"
  no_log: true