# Managed by ansible rclone-sync role.
# One line per job in format job_key|frequency_seconds|rclone_cmd|rclone_arg1|...|rclone_argN
{% for key, config in rclone_sync_config.dirs.items() %}
{{ key }}|{{ config.frequency_seconds }}{% for cmd in config.rclone_cmd %}|{{ cmd }}{% endfor %}{% for arg in rclone_sync_config.rclone_args + config.rclone_args %}|{{ arg }}{% endfor %}{{ '\n' }}{% endfor %}
