# Managed by ansible rclone-sync role.
# One line per directory in Format cmd|logprefix|src|dest|arg1|...|argN
# e.g. copy|wmt: |/mnt/wmt/|wmt:NDelius MIS Reports/Caseload Reports|--max-age=2m|-v
{% for key, config in rclone_sync_config.dirs.items() %}
[{{ key }}] {% for cmd in config.rclone_cmd %}|{{ cmd }}{% endfor %}{% for arg in rclone_sync_config.rclone_args + config.rclone_args %}|{{ arg }}{% endfor %}
{% endfor %}
