# Managed by ansible rclone-sync role.
# One line per directory in Format cmd|logprefix|src|dest|arg1|...|argN
# e.g. copy|wmt: |/mnt/wmt/|wmt:NDelius MIS Reports/Caseload Reports|--max-age=2m|-v
{% for key, config in rclone_sync_config.dirs.items() %}
{{ config.rclone_cmd }}|[{{ key }}] |{{ config.rclone_src }}|{{ config.rclone_dest }}{% for arg in rclone_sync_config.rclone_args + config.rclone_args %}|{{ arg }}{% endfor %}
{% endfor %}
