# Drop rclone-sync messages as it runs every minute and status us monitored through CloudWatch
if $msg contains "{{ rclone_sync_description }}" then stop
if $msg contains "rclone-sync.service: Succeeded" then stop
if $msg contains "rclone-sync.service: Failed with result" then stop
if $msg contains "rclone-sync.service: Main process exited" then stop
if $msg contains "INFO  : There was nothing to transfer" then stop
