---
# Configure Oracle database parameters for GoldenGate replication for a single database
# This file is called by configure_database_parameters.yml for each database SID

# The two _log_read database initialization parameters can improve performance of reading the redo log files by the
# LogMiner server by increasing the number and size of read buffers. These parameters also affect the same read
# buffers that are used during database media recovery, of which the performance may also improve.

# When using Extract in integrated capture mode, an area of Oracle memory called the Streams pool must be
# configured in the SGA of the database.
# 1GB per integrated extract/replicat process + 25% headroom
# MIS has one integrated extract and one integrated replicat process + 25% headroom = 2.5GB
# AUDIT has two integrated extract and one integrated replicat processes + 25% headroom = 5GB
- name: Set MIS specific streams_pool_size value
  when: 
    - run_mis is defined and run_mis
  set_fact:
    streams_pool_size: 2500M

- name: Set AUDIT specific streams_pool_size value
  when: 
    - run_auditdata is defined and run_auditdata
  set_fact:
    streams_pool_size: 5G

- name: Configure parameters in the database
  ansible.builtin.shell: |
    . ~/.bash_profile
    export ORACLE_SID="{{ oracle_goldengate_local_db_sid }}"
    export ORACLE_HOME="{{ oracle_goldengate_group.mis.oracle_home }}"
    export PATH="${ORACLE_HOME}/bin:${PATH}"

    SQL_CONNECT_STR="/ as sysdba"

    sqlplus -s "${SQL_CONNECT_STR}" << 'EOSQL'
    SET ECHO OFF
    SET FEEDBACK ON
    SET HEADING OFF
    SET PAGESIZE 0
    
    WHENEVER SQLERROR EXIT SQL.SQLCODE
    
    PROMPT Current ENABLE_GOLDENGATE_REPLICATION value:
    SELECT value FROM v$parameter WHERE name = 'enable_goldengate_replication';
    
    PROMPT Enable GoldenGate replication
    ALTER SYSTEM SET ENABLE_GOLDENGATE_REPLICATION=TRUE SCOPE=BOTH;
    
    PROMPT New ENABLE_GOLDENGATE_REPLICATION value:
    SELECT value FROM v$parameter WHERE name = 'enable_goldengate_replication';

    PROMPT Current _log_read_buffers value:
    SELECT value FROM v$parameter WHERE name = '_log_read_buffers';

    ALTER SYSTEM SET "_log_read_buffers"=64 SCOPE=SPFILE;

    PROMPT New _log_read_buffers value:
    SELECT value FROM v$parameter WHERE name = '_log_read_buffers';
    
    PROMPT Current _log_read_buffer_size value:
    SELECT value FROM v$parameter WHERE name = '_log_read_buffer_size';

    ALTER SYSTEM SET "_log_read_buffer_size"=256 SCOPE=SPFILE;
    
    PROMPT New _log_read_buffer_size value:
    SELECT value FROM v$parameter WHERE name = '_log_read_buffer_size';

    PROMPT Current streams_pool_size value:
    SELECT value FROM v$parameter WHERE name = 'streams_pool_size';

    ALTER SYSTEM SET streams_pool_size={{ streams_pool_size }} SCOPE=BOTH;

    PROMPT New streams_pool_size value:
    SELECT value FROM v$parameter WHERE name = 'streams_pool_size';

    EXIT
    EOSQL
  args:
    executable: /bin/bash
  register: sql_output
  become: yes 
  become_user: "{{ oracle_goldengate_owner }}"
  
- name: Display SQL output for {{ oracle_goldengate_local_db_sid }}
  ansible.builtin.debug:
    var: sql_output.stdout_lines
  when: sql_output is defined

- name: Check if SQL execution was successful for {{ oracle_goldengate_local_db_sid }}
  ansible.builtin.fail:
    msg: "Failed to configure database parameters for GoldenGate replication on {{ oracle_goldengate_local_db_sid }}. SQL output: {{ sql_output.stdout_lines }}"
  when: sql_output is defined and sql_output.rc != 0

