---
# create oracle_goldengate_sql_dir directory if it doesn't exist
- name: Ensure GoldenGate SQL directory exists
  ansible.builtin.file:
    path: "{{ oracle_goldengate_sql_dir }}"
    state: directory
    owner: "{{ oracle_goldengate_owner }}"
    group: "{{ oracle_goldengate_osgroup }}"
    mode: "0755"

- name: Deploy AuditData support packages
  when:
    - run_auditdata is defined and run_auditdata
  become: true
  become_user: "{{ oracle_goldengate_owner }}"
  block:
    - name: Set facts for Audit stream used in packages
      ansible.builtin.set_fact:
        oracle_goldengate_sql_owner: "{{ oracle_goldengate_group.auditdata.schema_owner }}"
        oracle_goldengate_source_schema_owner: "{{ oracle_goldengate_group.source.schema_owner | lower }}"
        oracle_goldengate_group_name: "auditdata"

    - name: Ensure AuditData SQL directory exists
      ansible.builtin.file:
        path: "{{ oracle_goldengate_sql_dir }}/auditdata"
        state: directory
        owner: "{{ oracle_goldengate_owner }}"
        group: "{{ oracle_goldengate_osgroup }}"
        mode: "0755"

    - name: Deploy AuditData support packages
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ oracle_goldengate_sql_dir }}/auditdata/{{ item | basename | regex_replace('\\.j2$', '') }}"
        owner: "{{ oracle_goldengate_owner }}"
        group: "{{ oracle_goldengate_osgroup }}"
        mode: "0644"
      loop: "{{ lookup('ansible.builtin.fileglob', role_path ~ '/templates/sql/auditdata/*.j2', wantlist=True) }}"

    - name: Run AuditData support package install
      ansible.builtin.shell: |
        . ~/.bash_profile
        export ORACLE_SID={{ oracle_goldengate_group.auditdata.tns_alias }}
        export ORACLE_HOME={{ oracle_goldengate_group.auditdata.oracle_home }}
        export PATH=${ORACLE_HOME}/bin:$PATH
        export ORAENV_ASK=NO
        . oraenv > /dev/null 2>&1
        cd {{ oracle_goldengate_sql_dir }}/auditdata
        sqlplus -s / as sysdba @install_auditdata_packages.sql
      args:
        executable: /bin/bash
      register: audit_config_output
      failed_when: audit_config_output.rc != 0

    - name: Show output of AuditData package install in logs
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ ['AuditData package install output:'] + (audit_config_output.stdout_lines | default([]) | map('trim') | select('truthy') | list) }}"
      when: "'ORA-' in audit_config_output.stdout or 'compilation errors' in audit_config_output.stdout"

    - name: Fail if ORA errors found in output of AuditData package install
      ansible.builtin.fail:
        msg: "Errors found in output of AuditData package install: {{ audit_config_output.stdout }}"
      when: "'ORA-' in audit_config_output.stdout or 'compilation errors' in audit_config_output.stdout"

    - name: Set execute permission for install_auditdata_db_links.sh script
      ansible.builtin.file:
        path: "{{ oracle_goldengate_sql_dir }}/auditdata/install_auditdata_db_links.sh"
        owner: "{{ oracle_goldengate_owner }}"
        group: "{{ oracle_goldengate_osgroup }}"
        mode: "0750"

    - name: Run AuditData db links install script install_auditdata_db_links.sh
      ansible.builtin.shell: |
        . ~/.bash_profile
        cd {{ oracle_goldengate_sql_dir }}/auditdata
        ./install_auditdata_db_links.sh
      args:
        executable: /bin/bash
      register: audit_db_links_output
      failed_when: audit_db_links_output.rc != 0

    - name: Show output of AuditData db links install in logs
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ ['AuditData db links install output:'] + (audit_db_links_output.stdout_lines | default([]) | map('trim') | select('truthy') | list) }}"
      when: audit_db_links_output.rc != 0

    - name: Fail if ORA errors found in output of AuditData db links install
      ansible.builtin.fail:
        msg: "Errors found in output of AuditData db links install: {{ audit_db_links_output.stdout }}"
      when: audit_db_links_output.rc != 0
