---
# Deploy Replicat parameter files based on which database is local
- name: Deploy Replicat parameter file for MIS
  ansible.builtin.template:
    src: replicat_mis.prm.j2
    dest: "{{ oracle_goldengate_param_dir }}/{{ oracle_goldengate_group.mis.replicat_name }}.prm"
    owner: "{{ oracle_goldengate_owner }}"
    group: "{{ oracle_goldengate_osgroup }}"
    mode: "0644"

# call task add_checkpointtable.yml to create the checkpoint table used by the replicat processes. We need to create it after deploying the parameter files because the parameter files specify the name of the checkpoint table, and it needs to exist before we can start the processes.
- name: Create checkpoint table for replicat processes
  import_tasks: add_checkpointtable.yml
  vars:
    checkpoint_table_db_alias: "{{ oracle_goldengate_group.mis.credential_alias }}"
