- name: Configure Oracle GoldenGate Manager
  become: true
  become_user: "{{ oracle_goldengate_owner }}"
  environment: "{{ gg_env }}"
  block:
    - name: Deploy GoldenGate Manager parameter file
      ansible.builtin.template:
        src: mgr.prm.j2
        dest: "{{ oracle_goldengate_param_dir }}/mgr.prm"
        owner: "{{ oracle_goldengate_owner }}"
        group: "{{ oracle_goldengate_osgroup }}"
        mode: "0644"

    - name: Stop Manager if it is already running before applying new configuration
      import_tasks: stop_mgr.yml

    - name: Start GoldenGate Manager
      import_tasks: start_mgr.yml

    - name: Check GoldenGate Manager status
      import_tasks: mgr_status.yml

    - name: Fail if Manager failed to start
      ansible.builtin.fail:
        msg: "GoldenGate Manager failed to start."
      when: not manager_is_running | default(false)
