---
# Start GoldenGate Replicat processes

- name: Start AUDITDATA Replicat process
  ansible.builtin.shell: |
    set -e
    set -o pipefail
    export ORAENV_ASK=NO
    . oraenv > /dev/null
    ./ggsci << EOF
    DBLOGIN USERIDALIAS AUDIT_DB
    START REPLICAT {{ oracle_goldengate_group.auditdata.replicat_name }}
    INFO REPLICAT {{ oracle_goldengate_group.auditdata.replicat_name }}
    EXIT
    EOF
  args:
    executable: /bin/bash
    chdir: "{{ oracle_goldengate_home }}"
  environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.auditdata.tns_alias}) }}"
  become: yes
  become_user: "{{ oracle_goldengate_owner }}"
  register: start_auditdata_replicat
  changed_when: "'RUNNING' in start_auditdata_replicat.stdout"
  when: run_auditdata

- name: Start AUDITREF Replicat process
  ansible.builtin.shell: |
    set -e
    set -o pipefail
    export ORAENV_ASK=NO
    . oraenv > /dev/null
    ./ggsci << EOF
    DBLOGIN USERIDALIAS AUDIT_DB
    START REPLICAT {{ oracle_goldengate_group.auditref.replicat_name }}
    INFO REPLICAT {{ oracle_goldengate_group.auditref.replicat_name }}
    EXIT
    EOF
  args:
    executable: /bin/bash
    chdir: "{{ oracle_goldengate_home }}"
  environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.auditref.tns_alias}) }}"
  become: yes
  become_user: "{{ oracle_goldengate_owner }}"
  register: start_auditref_replicat
  changed_when: "'RUNNING' in start_auditref_replicat.stdout"
  when: run_auditref

- name: Start MIS Replicat process
  ansible.builtin.shell: |
    set -e
    set -o pipefail
    export ORAENV_ASK=NO
    . oraenv > /dev/null
    ./ggsci << EOF
    DBLOGIN USERIDALIAS MIS_DB
    START REPLICAT {{ oracle_goldengate_group.mis.replicat_name }}
    INFO REPLICAT {{ oracle_goldengate_group.mis.replicat_name }}
    EXIT
    EOF
  args:
    executable: /bin/bash
    chdir: "{{ oracle_goldengate_home }}"
  environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.mis.tns_alias}) }}"
  become: yes
  become_user: "{{ oracle_goldengate_owner }}"
  register: start_mis_replicat
  changed_when: "'RUNNING' in start_mis_replicat.stdout"
  when: run_mis
