- name: Start GoldenGate Manager
  ansible.builtin.command: "{{ oracle_goldengate_scripts_dir }}/start_manager.sh"
  become: yes
  become_user: "{{ oracle_goldengate_owner }}"
  environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.mis.tns_alias}) }}"
  register: start_manager
  changed_when: "'started successfully' in start_manager.stdout"
  failed_when: start_manager.rc != 0
