---
# Stop GoldenGate Replicat processes

- name: Stop AUDITDATA Replicat process
  ansible.builtin.shell: |
    set -e
    set -o pipefail
    export ORAENV_ASK=NO
    . oraenv > /dev/null
    ./ggsci << EOF
    STOP REPLICAT {{ oracle_goldengate_group.auditdata.replicat_name }}
    INFO REPLICAT {{ oracle_goldengate_group.auditdata.replicat_name }}
    EXIT
    EOF
  args:
    executable: /bin/bash
    chdir: "{{ oracle_goldengate_home }}"
  environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.auditdata.tns_alias}) }}"
  become: yes
  become_user: "{{ oracle_goldengate_owner }}"
  register: stop_auditdata_replicat
  changed_when: "'STOPPED' in stop_auditdata_replicat.stdout or 'ABENDED' in stop_auditdata_replicat.stdout"
  when: run_auditdata

- name: Stop AUDITREF Replicat process
  ansible.builtin.shell: |
    set -e
    set -o pipefail
    export ORAENV_ASK=NO
    . oraenv > /dev/null
    ./ggsci << EOF
    STOP REPLICAT {{ oracle_goldengate_group.auditref.replicat_name }}
    INFO REPLICAT {{ oracle_goldengate_group.auditref.replicat_name }}
    EXIT
    EOF
  args:
    executable: /bin/bash
    chdir: "{{ oracle_goldengate_home }}"
  environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.auditref.tns_alias}) }}"
  become: yes
  become_user: "{{ oracle_goldengate_owner }}"
  register: stop_auditref_replicat
  changed_when: "'STOPPED' in stop_auditref_replicat.stdout or 'ABENDED' in stop_auditref_replicat.stdout"
  when: run_auditref

- name: Stop MIS Replicat process
  ansible.builtin.shell: |
    set -e
    set -o pipefail
    export ORAENV_ASK=NO
    . oraenv > /dev/null
    ./ggsci << EOF
    STOP REPLICAT {{ oracle_goldengate_group.mis.replicat_name }}
    INFO REPLICAT {{ oracle_goldengate_group.mis.replicat_name }}
    EXIT
    EOF
  args:
    executable: /bin/bash
    chdir: "{{ oracle_goldengate_home }}"
  environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.mis.tns_alias}) }}"
  become: yes
  become_user: "{{ oracle_goldengate_owner }}"
  register: stop_mis_replicat
  changed_when: "'STOPPED' in stop_mis_replicat.stdout or 'ABENDED' in stop_mis_replicat.stdout"
  when: run_mis
