---
# Unregister and manage AUDITDATA Extract process
- name: Unregister AUDITDATA Extract process
  when: oracle_goldengate_deploy_auditdata
  block:
    - name: Unregister AUDITDATA Extract process
      ansible.builtin.shell: |
        set -e
        set -o pipefail
        export ORAENV_ASK=NO
        . oraenv > /dev/null
        ./ggsci << EOF
        dblogin useridalias {{ oracle_goldengate_group.auditdata.credential_alias }}
        STOP EXTRACT {{ oracle_goldengate_group.auditdata.extract_name }}
        UNREGISTER EXTRACT {{ oracle_goldengate_group.auditdata.extract_name }} DATABASE
        DELETE EXTRACT {{ oracle_goldengate_group.auditdata.extract_name }}
        EXIT
        EOF
      args:
        executable: /bin/bash
        chdir: "{{ oracle_goldengate_home }}"
      environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.auditdata.tns_alias}) }}"
      become: yes
      become_user: "{{ oracle_goldengate_owner }}"
      register: remove_auditdata_extract
      failed_when: remove_auditdata_extract.rc != 0 and "already exists" not in remove_auditdata_extract.stderr
      changed_when: remove_auditdata_extract.rc == 0 and "already exists" not in remove_auditdata_extract.stderr

- name: Unregister AUDITREF Extract process
  when: oracle_goldengate_deploy_auditref
  block:
    - name: Unregister AUDITREF Extract process
      ansible.builtin.shell: |
        set -e
        set -o pipefail
        export ORAENV_ASK=NO
        . oraenv > /dev/null
        ./ggsci << EOF
        dblogin useridalias {{ oracle_goldengate_group.auditref.credential_alias }}
        STOP EXTRACT {{ oracle_goldengate_group.auditref.extract_name }}
        UNREGISTER EXTRACT {{ oracle_goldengate_group.auditref.extract_name }} DATABASE
        DELETE EXTRACT {{ oracle_goldengate_group.auditref.extract_name }}
        EXIT
        EOF
      args:
        executable: /bin/bash
        chdir: "{{ oracle_goldengate_home }}"
      environment: "{{ gg_env | combine({'ORACLE_SID': oracle_goldengate_group.auditref.tns_alias}) }}"
      become: yes
      become_user: "{{ oracle_goldengate_owner }}"
      register: remove_auditref_extract
      failed_when: remove_auditref_extract.rc != 0 and "already exists" not in remove_auditref_extract.stderr
      changed_when: remove_auditref_extract.rc == 0 and "already exists" not in remove_auditref_extract.stderr
