# Define the schemas whose activity is to be captured depending on the application
rat_capture_action: start
rat_capture_base_dir: /u02/rat-captures
rat_capture_s3_bucket_name: ""

application_schemas:
   delius-core:
      - DELIUS_APP_SCHEMA
      - DELIUS_POOL