---
- name: Get AppRegistration secrets
  import_role:
    name: secretsmanager-passwords
  vars:
    secretsmanager_passwords: "{{ rclone_secretsmanager_app_registrations }}"

- name: Get driveid secrets
  import_role:
    name: secretsmanager-passwords
  vars:
    secretsmanager_passwords: "{{ rclone_secretsmanager_drive_ids }}"

- name: Create rclone config dir
  ansible.builtin.file:
    path: "{{ rclone_config_dir }}"
    state: directory
    mode: '0700'
    owner: root
    group: root
  when: rclone_config_dir is defined

- name: Copy rclone config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rclone_config_dir }}/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - rclone.conf
