#!/bin/bash
#
# weblogic-all        Startup script for all weblogic components
#
# chkconfig: - 85 15
# description: weblogic server

# Source function library.
. /etc/init.d/functions

prog="weblogic-all"
unit_exists() {
  systemctl cat "$1" > /dev/null 2>&1
}

start_parallel() {
  set -e
  echo $"Starting all weblogic processes: "
  touch /var/lock/subsys/$prog

  unit_exists weblogic-node-manager && systemctl start weblogic-node-manager
  unit_exists weblogic-server && systemctl start weblogic-server
  unit_exists weblogic-ohs && systemctl start weblogic-ohs

  managed_services=$(find /etc/systemd/system/ -name 'WLS*.service' -exec basename {} \; | sort; echo "NOMIS_REPORTS_SERVER.service")
  echo -n $"Starting all WLS services in parallel: "
  i=0
  for managed_service in $managed_services; do
    systemctl start "$managed_service" > /dev/null 2>&1 &
    pids[i]=$!
    i=$((i + 1))
  done
  echo "PIDS ${pids[*]}"

  set +e
  i=0
  for managed_service in $managed_services; do
    echo -n $"Waiting for $managed_service: PID=${pids[i]}"
    if ! wait ${pids[i]}; then
      echo_failure
      echo
      return 1
    fi
    echo_success
    echo
    i=$((i + 1))
  done
  set -e
}

start_sequential() {
  set -e
  echo $"Starting all weblogic processes: "
  touch /var/lock/subsys/$prog
  unit_exists weblogic-node-manager && systemctl start weblogic-node-manager
  unit_exists weblogic-server && systemctl start weblogic-server
  managed_services=$(find /etc/systemd/system/ -name 'WLS*.service' -exec basename {} \; | sort; echo "NOMIS_REPORTS_SERVER.service")
  for managed_service in $managed_services; do
    systemctl start "$managed_service"
  done
  unit_exists weblogic-ohs && systemctl start weblogic-ohs
}

start() {
  start_parallel
}

stop() {
  set +e
  echo $"Stopping all weblogic processes: "
  rm -f /var/lock/subsys/$prog

  systemctl stop weblogic-ohs
  systemctl stop --no-block weblogic-server
  systemctl stop weblogic-node-manager
  pkill -9 -u oracle frmweb || true

  managed_services=$(find /etc/systemd/system/ -name 'WLS*.service' -exec basename {} \; | sort; echo "NOMIS_REPORTS_SERVER.service")
  for managed_service in $managed_services; do
    systemctl stop "$managed_service"
  done
}

status() {
  RETVAL=0
  echo $"Status of all weblogic processes:"
  if unit_exists weblogic-node-manager; then
    if ! systemctl status weblogic-node-manager; then
      RETVAL=1
    fi
  fi
  if unit_exists weblogic-ohs; then
      if ! systemctl status weblogic-ohs; then
        RETVAL=1
      fi
    fi
  if unit_exists weblogic-server; then
    if ! systemctl status weblogic-server; then
      RETVAL=1
    fi
  fi
  managed_services=$(find /etc/systemd/system/ -name 'WLS*.service' -exec basename {} \; | sort; echo "NOMIS_REPORTS_SERVER.service")
  for managed_service in $managed_services; do
    if ! systemctl status "$managed_service"; then
      RETVAL=1
    fi
  done
  return $RETVAL
}

restart() {
  stop
  start
}


get_unhealthy_services() {
  unhealthy=()
  if unit_exists weblogic-node-manager && \
     ! systemctl is-active --quiet weblogic-node-manager; then
    unhealthy+=(weblogic-node-manager)
  fi
  if unit_exists weblogic-ohs && \
     ! systemctl is-active --quiet weblogic-ohs; then
    unhealthy+=(weblogic-ohs)
  fi
  if unit_exists weblogic-server && \
     ! systemctl is-active --quiet weblogic-server; then
    unhealthy+=(weblogic-server)
  fi
  managed_services=$(find /etc/systemd/system/ -name 'WLS*.service' -exec basename {} \; | sort; echo "NOMIS_REPORTS_SERVER.service")
  for managed_service in $managed_services; do
    if ! systemctl is-active --quiet "$managed_service"; then
      unhealthy+=("$managed_service")
    fi
  done
  echo "${unhealthy[@]}"
}

healthcheck() {
  unhealthy_services=$(get_unhealthy_services)
  if [[ -z $unhealthy_services ]]; then
    echo -n $"Healthcheck of weblogic-all: "
    echo_success
    echo
    return 0
  else
    for service in $unhealthy_services; do
      echo -n $"Healthcheck of $service: "
      echo_failure
      echo
    done
    return 1
  fi
}

repair() {
  unhealthy_services=$(get_unhealthy_services)
  if [[ -z $unhealthy_services ]]; then
    echo "All services healthy, nothing to repair"
    return 0
  fi
  for service in $unhealthy_services; do
    systemctl restart "$service"
  done
  unhealthy_services=$(get_unhealthy_services)
  if [[ -z $unhealthy_services ]]; then
    echo "All services repaired"
    return 0
  fi
  echo "Failed to repair: $unhealthy_services"
  return 1
}

case "$1" in
  start)
    start
    repair
    unhealthy_services=$(get_unhealthy_services)
    if [[ -n $unhealthy_services ]]; then
      status
      echo "Re-starting all services in attempt to fix $unhealthy_services"
      stop
      start
      repair
    fi
    ;;
  start_sequential)
    start_sequential
    ;;
  start_parallel)
    start_parallel
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  healthcheck)
    healthcheck
    ;;
  repair)
    repair
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|healthcheck|repair|start_sequential|start_parallel}"
    exit 3
esac

exit $?
