---
- name: Copy WLST script to set overload protection options
  ansible.builtin.template:
    src: "12/home/oracle/admin/scripts/set_overload_protection.py.j2"
    dest: /home/oracle/admin/scripts/set_overload_protection.py
    owner: oracle
    group: oinstall
    mode: "0700"
    
- name: Set WebLogic overload protection options using WLST offline
  ansible.builtin.shell: |
    set -eo pipefail
    source ~oracle/.bash_profile
    /u01/app/oracle/Middleware/oracle_common/common/bin/wlst.sh \
    /home/oracle/admin/scripts/set_overload_protection.py > /home/oracle/admin/scripts/set_overload_protection.log 2>&1
  args:
    executable: /bin/bash
  become: yes
  become_user: oracle
  register: set_overload_protection_result
  changed_when: true