---
#rclone_target_version: latest # use this to install the latest version
rclone_target_version: 1.75.0
rclone_config_dir: "/root/.config/rclone"
rclone_secretsmanager_app_registrations: {}
rclone_secretsmanager_drive_ids: {}
rclone_sharepoint_config: {}

# example config
#rclone_secretsmanager_app_registrations:
#  rclone_1:
#    secret: "my_appregistration_secret"
#    users:
#      - client_id:
#      - client_secret:
#      - tenant_id:

#rclone_secretsmanager_drive_ids:
#  rclone_1:
#    secret: "my_driveid_secret"
#    users:
#      - MySharepointSiteId:

#rclone_sharepoint_config:
#  wmt:
#    app_registrations_ansible_key: rclone_1
#    drive_id_ansible_key: rclone_1
#    drive_id_secret_key: MySharepointSiteId
