---
#rclone_target_version: latest # use this to install the latest version
rclone_target_version: 1.75.0
rclone_config_dir: "/root/.config/rclone"
rclone_secretsmanager_app_registrations: {}
rclone_secretsmanager_drive_ids: {}
rclone_sharepoint_config: {}

# example config
#rclone_secretsmanager_app_registrations:
#  rclone:
#    secret: "my_appregistration_secret"
#    users:
#      - client_id:
#      - client_secret:
#      - tenant_id:

#rclone_secretsmanager_drive_ids:
#  rclone:
#    secret: "my_driveid_secret"
#    users:
#      - wmt:

#rclone_sharepoint_config:
#  wmt:
#    app_registrations_secret_key: rclone
#    drive_id_secrets_key: rclone
