$establishments = @{
  "AK" = "HMP ACKLINGTON" # unconfirmed exact match
  "STC2" = "STC RAINSBROOK" # unconfirmed exact match
  "AW" = "HMP ASHWELL" # unconfirmed exact match
  "AC" = "HMP ALTCOURSE" # unconfirmed exact match
  "BT" = "HMP BLAKENHURST" # unconfirmed exact match
  "BH" = "HMP BLANTYRE HOUSE" # unconfirmed exact match
  "BD" = "HMP BLUNDESTON" # unconfirmed exact match
  "BK" = "HMP BROCKHILL" # unconfirmed exact match
  "BU" = "HMP BULLWOOD HALL" # unconfirmed exact match
  "CH" = "HMP CAMP HILL" # unconfirmed exact match
  "CY" = "HMP CANTERBURY" # unconfirmed exact match
  "CS" = "HMP CASTINGTON" # unconfirmed exact match
  "DR" = "HMP DORCHESTER" # unconfirmed exact match
  "DV" = "Dover Immigration Removal Centre" # unconfirmed exact match
  "NE" = "HMP EDMUNDS HILL" # unconfirmed exact match
  "EV" = "HMP EVERTHORPE" # unconfirmed exact match
  "WN" = "HMYOI WERRINGTON"
  "AL" = "HMP ALBANY" # unconfirmed exact match
  "GP" = "HMP GLEN PARVA" # unconfirmed exact match
  "GL" = "HMP GLOUCESTER" # unconfirmed exact match
  "WY" = "HMYOI WETHERBY"
  "HR" = "Haslar Immigration Removal Centre" # unconfirmed exact match
  "HG" = "HMP HEWELL GRANGE" # unconfirmed exact match
  "AS" = "HMP ASHFIELD" # unconfirmed exact match
  "STC3" = "STC OAKHILL" # unconfirmed exact match
  "HY" = "HMP HOLLOWAY" # unconfirmed exact match
  "PT" = "HMP KINGSTON" # unconfirmed exact match
  "LA" = "HMP LANCASTER CASTLE" # unconfirmed exact match
  "LM" = "HMP LATCHMERE HOUSE" # unconfirmed exact match
  "FE" = "HMP FOSSE WAY" # unconfirmed exact match 
  "AA1" = "AA3 Prison for test" # unconfirmed exact match
  "FH" = "HMP FOSTON HALL"
  "HD" = "HMYOI HATFIELD"
  "HO" = "HMP HIGHDOWN"
  "HI" = "HMRC HINDLEY"
  "HB" = "HMP HOLLESLEY BAY"
  "HL" = "HMP HULL"
  "NN" = "HMP NORTHALLERTON" # unconfirmed exact match
  "LW" = "HMP LEWES"
  "LI" = "HMP LINCOLN"
  "LN" = "HMRC LOW NEWTON"
  "MD" = "HMP MOORLAND"
  "PK" = "HMP PARKHURST" # unconfirmed exact match
  "MH" = "HMP MORTON HALL"
  "NH" = "HMP NEW HALL"
  "NW" = "HMRC NORWICH"
  "PV" = "HMP PENTONVILLE"
  "PF" = "HMP PETERBOROUGH FEMALE" # unconfirmed exact match
  "RD" = "HMP READING" # unconfirmed exact match
  "PD" = "HMYOI PORTLAND"
  "RC" = "HMRC ROCHESTER"
  "SH" = "HMRC STOKE HEATH"
  "ST" = "HMP STYAL"
  "SM" = "HMP SHEPTON MALLET" # unconfirmed exact match
  "SY" = "HMP SHREWSBURY" # unconfirmed exact match
  "SU" = "HMP SUDBURY"
  "SN" = "HMP SWINFEN HALL"
  "TC" = "HMP THORN CROSS"
  "UK" = "HMP USK"
  "UP" = "HMP Prescoed"
  "WW" = "HMP WANDSWORTH"
  "WI" = "HMP WARREN HILL"
  "WC" = "HMP WINCHESTER"
  "WH" = "HMRC WOODHILL"
  "WS" = "HMP WORMWOOD SCRUBS"
  "WM" = "HMP WYMOTT"
  "WA" = "HMP THE WEARE" # unconfirmed exact match
  "WB" = "HMP WELLINGBOROUGH" # unconfirmed exact match
  "WO" = "HMP WOLDS" # unconfirmed exact match
  "FO" = "Foreign Prison" # unconfirmed exact match
  "TA" = "HMP THORP ARCH" # unconfirmed exact match
  "RU" = "HMP RUDGATE" # unconfirmed exact match
  "AN" = "HMP ALDINGTON" # unconfirmed exact match
  "CE" = "HMP CLELAND" # unconfirmed exact match
  "NO" = "HMP NORTHEYE" # unconfirmed exact match
  "PC" = "HMRC PUCKLECHURCH" # unconfirmed exact match
  "FI" = "HMYOI FINNAMORE" # unconfirmed exact match
  "CP" = "HMYOI CAMPSFIELD HOUSE" # unconfirmed exact match
  "OX" = "HMP OXFORD" # unconfirmed exact match
  "RL" = "HMP ROLLESTONE" # unconfirmed exact match
  "CR" = "HMYOI COLCHESTER" # unconfirmed exact match
  "ZZGH" = "Ghost Holding Establishment" # unconfirmed exact match
  "FB" = "Forest Bank (HMP & YOI)" # unconfirmed exact match
  "AG" = "HMP ASKHAM GRANGE"
  "KT" = "HMP KENNET" # unconfirmed exact match
  "BM" = "HMP BIRMINGHAM"
  "BX" = "HMP BRIXTON"
  "BC" = "BUCKLEY HALL"
  "BR" = "HMP Bure"
  "CW" = "HMP CHANNINGS WOOD"
  "CL" = "HMP COLDINGLEY"
  "DA" = "HMP DARTMOOR"
  "FS" = "HMP FEATHERSTONE"
  "MJW" = "Michael's Prison" # unconfirmed exact match
  "FD" = "HMP FORD"
  "ABC" = "HMP New Prison2" # unconfirmed exact match
  "FK" = "HMP FRANKLAND"
  "FN" = "HMP FULL SUTTON"
  "GH" = "HMP GARTH"
  "GT" = "HMP GARTREE"
  "GN" = "HMP GRENDON"
  "GM" = "HMP GUYS MARSH"
  "HV" = "HMP HAVERIGG"
  "HE" = "HMP HEWELL"
  "HP" = "HMP HIGHPOINT"
  "HM" = "HMP HUMBER"
  "HC" = "HMYOI HUNTERCOMBE"
  "PY" = "HMYOI PARC" # unconfirmed exact match
  "KM" = "HMP KIRKHAM"
  "LF" = "HMYOI LANCASTER FARMS"
  "LE" = "HMP LEEDS"
  "LC" = "HMP LEICESTER"
  "LY" = "HMP LEYHILL"
  "LH" = "HMP LINDHOLME"
  "LT" = "HMP LITTLEHEY"
  "LP" = "HMP LIVERPOOL"
  "LL" = "HMP LONG LARTIN"
  "MS" = "HMP MAIDSTONE"
  "NS" = "HMP NORTH SEA CAMP"
  "ON" = "HMP ONLEY"
  "RN" = "HMP RANBY"
  "RS" = "HMP RISLEY"
  "SD" = "HMP SEND"
  "SP" = "HMP SPRINGHILL"
  "SF" = "HMP STAFFORD"
  "SK" = "HMP STOCKEN"
  "SL" = "HMP SWALESIDE"
  "MT" = "HMP THE MOUNT"
  "VE" = "HMP THE VERNE"
  "WD" = "HMP WAKEFIELD"
  "WL" = "HMP WAYLAND"
  "WE" = "HMP WEALSTUN"
  "WT" = "HMP WHATTON"
  "WR" = "HMP WHITEMOOR"
  "AY" = "HMYOI AYLESBURY"
  "BF" = "HMP BEDFORD"
  "BA" = "HMP BELMARSH"
  "BW" = "HMP BERWYN"
  "BS" = "HMRC BRINSFORD"
  "BL" = "HMP BRISTOL"
  "BZ" = "HMP BRONZEFIELD" # unconfirmed exact match
  "BN" = "HMP Bullingdon"
  "CF" = "HMRC CARDIFF"
  "CD" = "HMP CHELMSFORD"
  "CK" = "HMP COOKHAM WOOD"
  "DT" = "HMYOI DEERBOLT"
  "DN" = "HMP DONCASTER" # unconfirmed exact match
  "DW" = "HMP DOWNVIEW"
  "DH" = "HMP DRAKE HALL"
  "FM" = "HMRC FELTHAM"
  "FY" = "HMYOI FELTHAM" # unconfirmed exact match
  "DM" = "HMP DURHAM"
  "ES" = "HMP EAST SUTTON PK"
  "EW" = "EHMP EASTWOOD PARK"
  "EY" = "HMP ELMLEY"
  "EE" = "HMP ERLESTOKE"
  "EX" = "HMP Exeter"
  "HH" = "HMP HOLME HOUSE"
  "IS" = "HMP ISIS"
  "DG" = "HMP DOVEGATE" # unconfirmed exact match
  "FW" = "HMP FiveWells"
  "LG" = "HMP LOWDHAM GRANGE" # unconfirmed exact match
  "NL" = "HMP Northumberland"
  "IW" = "HMP ISLE OF WIGHT"
  "KV" = "HMP KIRKLEVINGTON"
  "MR" = "HMP MANCHESTER"
  "NM" = "HMP NOTTINGHAM"
  "RH" = "HMP RYE HILL" # unconfirmed exact match
  "OW" = "HMP Oakwood"
  "PR" = "HMP PARC" # unconfirmed exact match
  "PB" = "HMP PETERBOROUGH" # unconfirmed exact match
  "PN" = "HMP PRESTON"
  "EH" = "HMP STANDFORD HILL"
  "SW" = "HMRC SWANSEA"
  "TS" = "HMP THAMESIDE" # unconfirmed exact match
  "MW" = "STC MEDWAY" # unconfirmed exact match
  "AZZ" = "AZZ Youth" # unconfirmed exact match
} 