#!/bin/bash

set -euo pipefail

# Gather Dictionary and Fixed Object Statistics

# We need to explicitly exclude the SYS.HIST_AUD$ table if it exists in this database
# because it is huge and gathering statistics on it will take many hours.
sqlplus -s / as sysdba <<EOSQL

WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT FAILURE

ALTER USER HOTPAGE_AQ IDENTIFIED BY HOTPAGE_AQ ACCOUNT UNLOCK;
ALTER USER TAGSAR IDENTIFIED BY TAGSAR ACCOUNT UNLOCK;
ALTER USER TAGMERGE IDENTIFIED BY TAGMERGE ACCOUNT UNLOCK;
ALTER USER TAGWF1 IDENTIFIED BY TAGWF1 ACCOUNT UNLOCK;
ALTER USER TAGWF2 IDENTIFIED BY TAGWF2 ACCOUNT UNLOCK;
ALTER USER TAGWFC1 IDENTIFIED BY TAGWFC1 ACCOUNT UNLOCK;
ALTER USER TAGWFC2 IDENTIFIED BY TAGWFC2 ACCOUNT UNLOCK;
EXIT

EOSQL
