#!/bin/bash

set -euo pipefail

# Individually recompile triggers which are not getting recompiled.


sqlplus -s / as sysdba <<EOSQL

WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT FAILURE

ALTER TRIGGER OMS_OWNER.OFFENDER_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFFENDER_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_ALERTS_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_ASSESSMENTS_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_BOOKINGS_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_CASE_OFFICER_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_EXT_MOV_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_IEP_LEVEL_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_LANGUAGE_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_OIC_SANCTION_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_PROF_DETAILS_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_SUB_ACCOUNTS_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.OFF_IMPRISON_STS_API_EVENT COMPILE;
ALTER TRIGGER 		OMS_OWNER.CASE_NOTES_API_EVENT COMPILE;
ALTER SYNONYM API_USER.API_OFFENDER_PROCS COMPILE;
alter package OMS_OWNER.SECURITY_ALERT COMPILE body;

GRANT EXECUTE ON SYS.DBMS_LOCK TO DMSYS;




EXIT

EOSQL
